dictionaryDefinitions:
  - name: myWords
    path: ./.dictionary/custom.txt
    addWords: true
dictionaries:
  - myWords
ignorePaths:
  - "**/migrations/**"
  - "**/node_modules/**"
  - "**/.vscode/**"
