# Generated by Django 4.1.5 on 2023-02-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('a1_diesel_consumed', models.FloatField(default=0)),
                ('a2_diesel_consumed', models.FloatField(default=0)),
                ('a3_diesel_consumed', models.FloatField(default=50)),
                ('a3_electricity_consumed_kwh', models.FloatField(blank=True)),
                ('a3_electricity_consumed_litres', models.FloatField(blank=True)),
                ('a3_feedstock_preparation', models.FloatField(default=0)),
                ('a3_propane_consumption', models.FloatField(default=0)),
                ('a3_stack_emissions_n20', models.FloatField(default=0)),
                ('a3_stack_emissions_ch4', models.FloatField(default=0)),
                ('a3_stack_emissions_c02', models.FloatField(default=0)),
                ('a4_diesel_consumed', models.FloatField(default=0)),
            ],
        ),
    ]
