version: "3.9"

services:
  web:
    build: .
    container_name: "backend"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    tty: true
    environment:
      - ENVIRONMENT=production
      - REDIS_CHANNELS_HOST=redis_channels
    env_file:
      - .env.production
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: "crumpet_postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crumpet_db
      POSTGRES_USER: head_baker
      POSTGRES_PASSWORD: Crumpet2023
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_channels:
    image: "redis:latest"
    container_name: "crumpet_redis_channels"
    ports:
      - "6379:6379"
    volumes:
      - redis_channels_data:/data

volumes:
  pgdata:
  redis_channels_data:


