version: "3.9"

services:
  web:
    build: .
    container_name: "crumpet-backend-dev"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    tty: true
    env_file:
      - .env.development
    depends_on:
      - db
      - message-broker

  celery:
    build: .
    container_name: "crumpet-celery-worker-dev"
    command: celery -A backend worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env.development
    depends_on:
      - web
      - message-broker

  db:
    image: postgres:15
    container_name: "crumpet-postgres-dev"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  message-broker:
    image: "redis:latest"
    container_name: "crumpet-redis-message-broker-dev"
    ports:
      - "6379:6379"

  # redis_channels:
  #   image: "redis:latest"
  #   container_name: "crumpet_redis_channels_DEV"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_channels_data:/data

volumes:
  pgdata:
    # redis_channels_data:


