# Generated by Django 4.1.5 on 2024-02-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowschema",
            name="identifier",
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stepschema",
            name="identifier",
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transitionschema",
            name="identifier",
            field=models.SlugField(max_length=100),
        ),
    ]
