# Generated by Django 4.1.5 on 2023-09-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_project_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="api_key",
            field=models.CharField(
                default="PhZIZWGhUv2snEoQ5S4G3O1FQ608FUx8", max_length=256, unique=True
            ),
        ),
    ]
