# Generated by Django 4.1.5 on 2023-03-01 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_name', models.CharField(max_length=20)),
                ('margin_top', models.IntegerField(default=0)),
                ('margin_right', models.IntegerField(default=0)),
                ('margin_bottom', models.IntegerField(default=0)),
                ('margin_left', models.IntegerField(default=0)),
                ('padding_top', models.IntegerField(default=0)),
                ('padding_right', models.IntegerField(default=0)),
                ('padding_bottom', models.IntegerField(default=0)),
                ('padding_left', models.IntegerField(default=0)),
                ('flex', models.IntegerField(default=1)),
                ('main_axis_alignment', models.CharField(blank=True, choices=[('start', 'start'), ('center', 'center'), ('end', 'end')], max_length=50, null=True)),
                ('cross_axis_alignment', models.CharField(blank=True, choices=[('start', 'start'), ('center', 'center'), ('end', 'end')], max_length=50, null=True)),
                ('main_axis_size', models.IntegerField(blank=True, null=True)),
                ('spacing', models.CharField(blank=True, choices=[('flex', 'flex')], max_length=50, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('font_size', models.IntegerField(blank=True, null=True)),
                ('font_color', models.IntegerField(blank=True, null=True)),
                ('background_color', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('button_action', models.CharField(blank=True, choices=[('close', 'close'), ('deep_link', 'deep_link'), ('external_link', 'external_link'), ('next', 'next')], max_length=15, null=True)),
                ('stroke', models.IntegerField(blank=True, null=True)),
                ('stroke_color', models.CharField(blank=True, max_length=50, null=True)),
                ('border_radius', models.IntegerField(blank=True, null=True)),
                ('allow_multi_selection', models.BooleanField(blank=True, null=True)),
                ('selector_count', models.IntegerField(blank=True, null=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('increment', models.IntegerField(blank=True, null=True)),
                ('label_text', models.TextField(blank=True, null=True)),
                ('slider_color', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.element')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('event_type', models.CharField(choices=[('generic', 'Generic Event'), ('button_pressed', 'Button Pressed'), ('text_field_value', 'Textfield Value'), ('selection_confirmed', 'Selection')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('value', models.TextField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='app.element')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='trigger_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_elements', to='app.event'),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.element',),
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.element',),
        ),
    ]
