# Generated by Django 4.1.5 on 2024-03-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_flowschema_identifier_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="environment",
            options={"verbose_name": "Environment", "verbose_name_plural": "Environments"},
        ),
        migrations.RemoveConstraint(
            model_name="transitionschema",
            name="unique_identifier_for_outgoing_transitions",
        ),
        migrations.AddConstraint(
            model_name="flowinstance",
            constraint=models.UniqueConstraint(
                fields=("person", "schema_version"), name="unique_person_schema_version"
            ),
        ),
    ]
