# Generated by Django 4.1.5 on 2023-09-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_project_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="api_key",
            field=models.CharField(
                default="<function uuid4 at 0x105dc6200>", max_length=256, unique=True
            ),
        ),
    ]
