# Generated by Django 4.1.5 on 2023-03-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_element_parent_alter_element_trigger_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='proxy_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
