# Generated by Django 4.1.5 on 2023-03-02 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_element_proxy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextElement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.element',),
        ),
        migrations.AlterField(
            model_name='element',
            name='font_size',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(128)]),
        ),
        migrations.DeleteModel(
            name='Selector',
        ),
    ]
