# Generated by Django 4.1.5 on 2023-09-08 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_project_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="api_key",
            field=models.CharField(default=uuid.uuid4, max_length=256, unique=True),
        ),
    ]
