# Generated by Django 4.1.5 on 2023-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="data_schema",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
