# Generated by Django 4.1.5 on 2023-03-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_element_font_color_alter_element_font_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonElement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.element',),
        ),
        migrations.CreateModel(
            name='ImageElement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.element',),
        ),
        migrations.AlterField(
            model_name='element',
            name='border_radius',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='stroke',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
