# Generated by Django 4.1.5 on 2023-12-01 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_environment_data_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("properties", models.JSONField()),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="app.environment",
                    ),
                ),
            ],
        ),
    ]
