# Generated by Django 4.1.5 on 2023-12-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonSchema",
            fields=[
                ("schema", models.JSONField()),
                (
                    "environment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="people_schema",
                        serialize=False,
                        to="app.environment",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="environment",
            name="data_schema",
        ),
    ]
