# Generated by Django 4.1.5 on 2023-03-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_trigger_event_element_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.element',),
        ),
    ]
