# Generated by Django 4.1.5 on 2023-03-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_selectiongroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('value', models.TextField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='app.element')),
            ],
        ),
    ]
