# Generated by Django 4.1.5 on 2023-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_element_selector_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.element',),
        ),
        migrations.AlterField(
            model_name='element',
            name='increment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
