# Generated by Django 4.1.5 on 2023-03-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_slider_alter_element_increment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextField',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.element',),
        ),
    ]
