name: Backend QA

on:
  pull_request:
    branches:
      - master


permissions: read-all

jobs:
  Tests:
    defaults:
      run:
        working-directory: ./backend
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: [self-hosted, linux, omen]
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        run: docker compose run web python manage.py test
